
package net.visualflip.lextouch.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * Tue May 27 16:24:28 COT 2014
 * Generated source version: 2.7.7.redhat-1
 */

@XmlRootElement(name = "buscarPorId", namespace = "http://lextouch-rfiscal.rhcloud.com/Usuario")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "buscarPorId", namespace = "http://lextouch-rfiscal.rhcloud.com/Usuario")

public class BuscarPorId {

    @XmlElement(name = "id")
    private int id;

    public int getId() {
        return this.id;
    }

    public void setId(int newId)  {
        this.id = newId;
    }

}

