
package net.visualflip.lextouch.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * Tue May 27 16:24:28 COT 2014
 * Generated source version: 2.7.7.redhat-1
 */

@XmlRootElement(name = "buscarPorIdResponse", namespace = "http://lextouch-rfiscal.rhcloud.com/Usuario")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "buscarPorIdResponse", namespace = "http://lextouch-rfiscal.rhcloud.com/Usuario")

public class BuscarPorIdResponse {

    @XmlElement(name = "buscarPorId")
    private java.lang.String buscarPorId;

    public java.lang.String getBuscarPorId() {
        return this.buscarPorId;
    }

    public void setBuscarPorId(java.lang.String newBuscarPorId)  {
        this.buscarPorId = newBuscarPorId;
    }

}

